development:
  adapter: postgresql
  encoding: unicode
  database: faskyn_development
  pool: 5
  username: Silo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: faskyn_test
  pool: 5
  username: Silo
  password:

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV['MAX_THREADS'] || 5 %>

